name: Automated niv-managed dependency updates
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run this every day at 4:00am
    - cron:  '0 4 * * *'
jobs:
  niv-updater:
    name: 'Create PRs for niv-managed dependencies'
    runs-on: ubuntu-latest
    steps:
      # notice there is no checkout step
      - name: niv-updater-action
        uses: knl/niv-updater-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The path in the repo to the sources.json file
          sources_file: 'nix/sources.json'
          # The prefix to add to every created branch
          branch_prefix: 'update/'
          # If there are revisions in form 'v1.2' (not SHAs), skip updating them
          skip_versioned_revisions: true
          # Do not skip dependencies in repos accessed via ssh from updating
          skip_ssh_repos: false
          # Let's not show merges in the changelog
          show_merges: false
          # Have some prefix and a suffix. Use '|' to keep newlines
